POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "Kyle",
    "password": "password",
    "email": "kyle@gmail.com",
    "profile": "profile"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "name": "ram@gmail.com",
    "password": "12345678910"
}

###
GET http://localhost:3001/api/user/

###
PUT http://localhost:3001/users/1
Content-Type: application/json

{
    "profile": "picture"
}

###
GET http://localhost:3001/api/products

###
POST http://localhost:3001/api/products/pro
Content-Type: application/json

{
    "productName": "Hoodie",
    "fabric": "Cotton",
    "weight": 110,
    "meterSquare": 290,
    "color": "Black",
    "date": "2023-08-07T00:00:00.000Z",
    "size": ["S","M","L"],
    "perSize": "290/[S,M,L]"
}

